#!/bin/sh

# ${XDG_CONFIG_HOME}/bspwm/rules/spotify
#
# bspwm external rules to force spotify to a given desktop

# Set variables
__win_id="${1?}"
__win_class="${2}"
__atom="_NET_WM_PID"
__desktop="9"

# Ignore STDERR output
exec 2>/dev/null

# Only process windows of undefined class
if [ "${__win_class}" = "" ]; then
	__pid="$( xprop -id "${__win_id:?}" -notype -f "${__atom}" 32c '=$0' "${__atom}" | cut -d= -f2 )"
	# If it's spotiyf, move it to the correct desktop
	if [ "$(ps -p "${__pid:?}" -o comm= )" = "spotify" ]; then
		echo desktop="^${__desktop}";
	fi
fi

# Unset variables
unset __win_id __win_class __atom __desktop __pid
