# ${ZDOTDIR}/zshenv
#
# Environment file for zsh shells
# Read for every shell

# Source environment.d config file if it exists
if [[ -f "${HOME}/.config/environment.d/00-zsh.conf" ]]; then
	. "${HOME}/.config/environment.d/00-zsh.conf"
fi

# Update path
path+=( "${HOME}/.local/bin" )
export PATH
