#!/usr/bin/bash

# ${BASHDOTDIR}/keybinds
#
# Bash-specific keybindings

# Search throuh history for partial commands
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

bind '"\e[H": beginning-of-line'
bind '"\e[F": end-of-line'
bind '"\eOH": beginning-of-line'
bind '"\eOF": end-of-line'
bind '"\e[1~": beginning-of-line'
bind '"\e[4~": end-of-line'
bind '"\e[7~": beginning-of-line'
bind '"\e[8~": end-of-line'

bind '"\e[3~": delete-char'

