#!/bin/bash

# Starts all required sockets and applications to enable yubikey in WSL.
# Requires gpg and pageant installed on windows host, and key connected
#     to host already (use gpg --card-status in powershell).


wsl_load_key() {
	pageant_bin="$HOME"/.config/ssh/wsl2-ssh-pageant.exe
	[[ ! -x "$pageant_bin" ]] &&
		echo >&2 "ERROR: ${pageant_bin} is not executable." &&
		unset pageant_bin &&
		return

	export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
	export GPG_AGENT_SOCK=$(gpgconf --list-dirs agent-socket)
	[[ "${SSH_AUTH_SOCK}" == "" || "${GPG_AGENT_SOCK}" == "" ]] &&
		echo >&2 "ERROR: Socket variables are incorrect." &&
		return
	rm -rf "$SSH_AUTH_SOCK"
	rm -rf "$GPG_AGENT_SOCK"
	setsid nohup socat UNIX-LISTEN:"$SSH_AUTH_SOCK,fork" EXEC:"$pageant_bin" &>/dev/null
	setsid nohup socat UNIX-LISTEN:"$GPG_AGENT_SOCK,fork" EXEC:"$pageant_bin -gpgConfigBasepath 'C:/Users/Darren/AppData/Local/gnupg' -gpg S.gpg-agent" &>/dev/null

	unset pageant_bin

	if ! gpg --card-status &>/dev/null && [[ $GPG_CHECK != true ]]; then
		export GPG_CHECK=true
		wsl_load_key
		unset GPG_CHECK
		if gpg --card-status; then
			printf 'Yubikey loaded successfully.\n'
		else
			printf 'ERROR: Yubikey not detected.\n'
		fi
	else
		printf 'Yubikey loaded successfully.\n'
	fi
}
