# ${HOME}/.config/environment.d/00-bash.conf
#
# Load environment files for bash

source $HOME/.config/environment.d/10-xdg.conf
source $HOME/.config/environment.d/20-other.conf

export PATH="${HOME}"/.local/bin:$PATH
