# ${HOME}/.config/environment.d/10-xdg.conf
#
# Environment variables to set XDG directories

# XDG base directories
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# XDG user directories
export XDG_DESKTOP_DIR="${HOME}/Desktop"
export XDG_DOCUMENTS_DIR="${HOME}/Documents"
export XDG_DOWNLOAD_DIR="${HOME}/Downloads"
export XDG_MUSIC_DIR="${HOME}/Music"
export XDG_PICTURES_DIR="${HOME}/Pictures"
export XDG_PUBLICSHARE_DIR="${HOME}/Public"
export XDG_TEMPLATES_DIR="${HOME}/Templates"
export XDG_VIDEOS_DIR="${HOME}/Videos"

# X11 directories
export XINITRC="${XDG_CONFIG_HOME}/X11/xinitrc"
export XSERVERRC="${XDG_CONFIG_HOME}/X11/xserverrc"

# Other applications that don't natively support XDG
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export TMUX_PLUGIN_MANAGER_PATH="${XDG_CONFIG_HOME}/tmux/plugins/"
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"

# Custom XDG workarounds
export SSH_CONFIG="${XDG_CONFIG_HOME}/ssh/config"
export GIT_SSH_COMMAND="/usr/bin/ssh -F \"${SSH_CONFIG}\""
