# ${HOME}/.config/environment.d/10-xdg.conf
#
# Environment variables to set XDG directories
# NB. User directories are set in ${HOME}/user-dirs.dirs

# XDG base directories
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# X11 directories
export XINITRC="${XDG_CONFIG_HOME}/X11/xinitrc"
export XSERVERRC="${XDG_CONFIG_HOME}/X11/xserverrc"

# Other applications that don't natively support XDG
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export TMUX_PLUGIN_MANAGER_PATH="${XDG_CONFIG_HOME}/tmux/plugins/"
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"

# Custom XDG workarounds
export SSH_CONFIG="${XDG_CONFIG_HOME}/ssh/config"
