#!/usr/bin/zsh

# ${XDG_CONFIG_HOME}/shell/zsh/zshrc
#
# Main rc file for zsh shells
# Loaded only for interactice shells

# Report errors if glob doesn't match anything
setopt nomatch

# Notify of job completion immediately
setopt notify

# Disable audible bell
unsetopt beep

# Make traversing directories easier
export DIRSTACKSIZE=12
setopt autocd autopushd pushdsilent pushdtohome

# Use vi mode and shorten keyress timeout for mode changes
bindkey -v
export KEYTIMEOUT=10

# Enable zsh hooks
autoload -Uz add-zsh-hook

# Sync history after each command
# Note in ZSH, this requires ensuring no metadata is kept when sharing a 
# histfile with bash, which is why SHARE_HISTORY is not used and instead
# a precmd hook is added
unsetopt EXTENDED_HISTORY SHARE_HISTORY
setopt INC_APPEND_HISTORY
__sync_history() {
	fc -R "$HISTFILE"
}
add-zsh-hook precmd __sync_history

# Refresh TTY before every command
__update_gpg_tty() {
    echo UPDATESTARTUPTTY | gpg-connect-agent &>/dev/null
}
add-zsh-hook preexec __update_gpg_tty

# Load zsh-specific modules
source "${ZDOTDIR}"/completion
source "${ZDOTDIR}"/keybinds
source "${ZDOTDIR}"/prompt
